### ISSUE TITLE
My account redirection after successful login

### ISSUE THREAD

**Issue by FredrikMBP** [jamieblomerus/WP-Mobile-BankID-Integration#35]
After the user has successfully logged in using BankID the script will automatically redirect the user to /my-account. 

Hardcoding this redirection can be avoided by using woocommerce helper functions to fetch the permalink as it might be different depending on the users setup. In my case its "/mitt-konto".

In woocommerce.php line 104, update from 

`$this->login_button( '/my-account' );`

to

`$this->login_button( wc_get_page_permalink( 'myaccount' ) );`
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #35</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @FredrikMBP</code> (replace <code>20</code> with the amount, and <code>@FredrikMBP</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

**Comment by jamieblomerus** [comment]
This issue has been resolved in PR #36 and the bugfix will be part of the next release (1.4.1).
